chollada_ams_6feb23_pt37/urls.py
from django.contrib import admin
from django.urls import path, include
from my_app import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.CholladaHomePage.as_view(template_name='my_app/Chollada_Apartment.html'), name='Chollada_Apartment'),

    # path('users/', include('users.urls',namespace='users')),
    path('users/', include('users.urls')),
    # path('users/', include('django.contrib.auth.urls')),

    # path('my_app/', include('my_app.urls', namespace='my_app')),
    path('my_app/', include('my_app.urls')),
    path('my_app/', include('django.contrib.auth.urls')),

]

admin.site.site_header = 'Chollada Apartment Administration'

my_app/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('admin_page/', views.admin_page, name='admin_page'),
    path('', views.gateway, name='gateway'),  # one only ... blank ('')
    path('create_contract/', views.create_contract, name='create_contract'),
    path('billing/', views.billing, name='billing'),
    path('month_bills/', views.month_bills, name='month_bills'),

    path('pay_bill/<str:bref>/', views.pay_bill, name='pay_bill'),

    path('report_type/', views.report_type, name='report_type'),
    path('report_parameters/', views.report_parameters, name='report_parameters'),
    path('extra_rates/', views.extra_rates, name='extra_rates'),
    path('elec_cpu_change/', views.elec_cpu_change, name='elec_cpu_change'),
    path('water_cpu_change/', views.water_cpu_change, name='water_cpu_change'),
    path('room_type_rate/', views.room_type_rate, name='room_type_rate'),
    path('current_tenants/', views.current_tenants, name='current_tenants'),

    path('vacant_rooms/', views.vacant_rooms, name='vacant_rooms'),
    path('update_room_status/<str:rmn>/', views.update_room_status, name='update_room_status'),

    path('monthly_report/', views.monthly_report, name='monthly_report'),
    path('misc_contents/', views.misc_contents, name='misc_contents'),

    path('manage_users/', views.manage_users, name='manage_users'),
    path('user_list_to_delete/', views.user_list_to_delete, name='user_list_to_delete'),
    path('delete_user/<str:rmn>/', views.delete_user, name='delete_user'),
    path('confirm_delete_user/<str:k>/', views.confirm_delete_user, name='confirm_delete_user'),

    path('register/', views.Register.as_view(), name='register'),
    path('register/done/', views.register_done, name='register_done'),
    path('change_password/', views.change_password, name='change_password'),
    path('maintenance_charge/', views.maintenance_charge, name='maintenance_charge'),
    path('new_tenant/', views.new_tenant, name='new_tenant'),
    path('tenant_profile/', views.tenant_profile, name='tenant_profile'),
    path('tenant_bill/', views.tenant_bill, name='tenant_bill'),
    path('tenant_info/', views.tenant_info, name='tenant_info'),

]

users/urls.py
from django.urls import path

from . import views

# app_name='users'

urlpatterns = [
    # path('register/', views.Register.as_view(), name='register'),
    # path('register/done/', views.register_done, name='register_done')
]

my_app/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model

CUser = get_user_model()  # Custom User


class Room_type(models.Model):
    description = models.CharField(max_length=250)
    rate = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.description


class Room(models.Model):
    class Status(models.TextChoices):
        VACANT = 'ว่าง', 'ว่าง'  # (VACANT: Name, vacant: value, VA: label[admin])
        BOOKED = 'ไม่ว่าง', 'ไม่ว่าง'
        RESERVED = 'จอง', 'จอง'

    room_type = models.ForeignKey(Room_type, on_delete=models.CASCADE)
    room_no = models.CharField(max_length=4)
    status = models.CharField(max_length=8, choices=Status.choices, default=Status.VACANT)
    exmovein_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.room_no

    def get_absolute_url(self):
        return reverse('update_room_status', args=[str(self.room_no)])


class Extra(models.Model):
    description = models.CharField(max_length=100)
    cpu = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.description


class Billing(models.Model):
    STATUS_CHOICE = (('open', 'OPEN'), ('close', 'CLOSE'),)

    bill_ref = models.CharField(max_length=6)
    bill_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')
    tenant_name = models.CharField(max_length=100)
    room_no = models.CharField(max_length=4)
    room_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    room_acc_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    electricity_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    water_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    common_ser_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    other_ser_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    overdue_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    adjust = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    bill_total = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    payment_date = models.DateField(blank=True, null=True)
    payment_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    cf_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    late_fee = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    maint_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    class Meta:
        ordering = ('-bill_date',)

    def __str__(self):
        return 'Bill for room number: {} Status: {}'.format(self.room_no, self.status)

    def get_absolute_url(self):
        return reverse('pay_bill', args=[str(self.bill_ref)])


class TenantProfile(models.Model):
    # tenant = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tenant = models.OneToOneField(CUser, on_delete=models.CASCADE)
    pin = models.CharField(max_length=13, unique=True)
    phone = models.CharField(max_length=10)
    # room_no = models.OneToOneField(Room, on_delete=models.CASCADE, unique=True)
    room_no = models.OneToOneField(Room, on_delete=models.CASCADE, unique=True)
    term = models.PositiveSmallIntegerField(default=12)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    deposit = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    deduct = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    cum_ovd = models.DecimalField(max_digits=7, decimal_places=2, blank=True, default=0)
    adjust = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    extra = models.ManyToManyField(Extra)

    # bill_date = models.DateField(auto_now=True, blank=True) # DELETED 24Jan23
    bill_ref = models.CharField(max_length=6, blank=True)  # ADDED 24Jan23

    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    # USE PLACEHOLDER (NO DEFAULT VALUE) INITIAL VALUE TO BE PROVIDED WHEN SAVE TO DB
    elec_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    water_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    late_fee = models.DecimalField(max_digits=7, decimal_places=2, default=0)  # no need to use placeholder
    maint_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return 'Profile for user {}'.format(self.tenant.first_name)

    def get_absolute_url(self):
        return reverse('fill_bill', args=[self.room_no])

    #
    # def get_absolute_url(self):
    #     return reverse('fill_bill', args=[self.room_no])

    # def get_absolute_url(self):
    #     return reverse('blog:post_detail',
    #                    args=[self.publish.year,
    #                          self.publish.month,
    #                          self.publish.day,
    #                          self.slug])


class MaintenanceService(models.Model):
    job_ref = models.CharField(max_length=6)
    job_date = models.DateField(auto_now_add=True)

    room_no = models.CharField(max_length=4)
    description = models.CharField(max_length=100, default='Maintenance Charge')
    job_cost = models.DecimalField(max_digits=7, decimal_places=2)

    class Meta:
        ordering = ('-job_date',)

    def __str__(self):
        return 'Job_Ref.: {}'.format(self.job_ref)

my_app/forms.py
from django import forms
from .models import TenantProfile, Room

from django.contrib.auth import get_user_model

CUser = get_user_model()


class TenantCreateForm(forms.ModelForm):
    password1 = forms.CharField(label='Password1', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password2', widget=forms.PasswordInput)
    class Meta:
        model = CUser
        fields = ('username', 'first_name', 'last_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


    # def clean_email(self):
    #     data = self.cleaned_data['email']
    #     if CUser.objects.filter(email=data).exists():
    #         # if settings.AUTH_USER_MODEL.objects.filter(email=data).exists():
    #         raise forms.ValidationError('Email already in use.')
    #     return data


class TenantProfileCreateForm(forms.ModelForm):
    class Meta:
        model = TenantProfile
        # fields = {'pin', 'phone','photo', 'room_no', 'term', 'start_date', 'end_date', 'deposit', 'adjust', 'extra'}
        fields = {'pin','phone','term','start_date','deposit','adjust','extra'}


class PaymentForm(forms.Form):
    payment_amount = forms.DecimalField(max_digits=7, decimal_places=2,
                                        widget=forms.NumberInput(
                                            attrs={'class': 'paid_amount', 'placeholder': 'amount', 'min': 0}))
    payment_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'class': 'pay_date', 'placeholder': 'date'}))


class BookRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = {'status','exmovein_date'}

        widgets = {
            'status': forms.Select(attrs={'class': 'status'}),
            'exmovein_date': forms.DateInput(attrs={'class': 'exmovein_date','placeholder': 'date'})
        }



class Elec_cpu_change(forms.Form):
    elec_cpu = forms.DecimalField(max_digits=7, decimal_places=2,
                                  widget=forms.NumberInput(
                                      attrs={'class': 'elec_cpu', 'placeholder': 'elec_cpu', 'min': 0}))


class Water_cpu_change(forms.Form):
    water_cpu = forms.DecimalField(max_digits=7, decimal_places=2,
                                   widget=forms.NumberInput(
                                       attrs={'class': 'water_cpu', 'placeholder': 'water_cpu', 'min': 0}))

#
# class PhoneNoMessage(forms.Form):
#     phone_no = forms.CharField(max_length=10)
#     sms_msg = forms.CharField(widget=forms.Textarea)
#     # msg = forms.CharField(widget=forms.TextInput( attrs={'class': 'msg'}))


class BillForm(forms.ModelForm):
    class Meta:
        model = TenantProfile
        fields = {'elec_unit', 'water_unit'}
        widgets = {
            'elec_unit': forms.NumberInput({'class': 'eu', 'placeholder': 'elect-unit', 'min': 0}),
            'water_unit': forms.NumberInput(attrs={'class': 'wu', 'placeholder': 'water-unit', 'min': 0})
        }

templates/my_app/admin_page.html
{% extends "app_base_html.html" %}
{% load static %}

{% block title %}Admin page{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
{% endblock %}

templates/my_app/billing.html
{% extends 'app_base_html.html' %}
{% load static %}

{% load ams_tags %}

{% block title %}Create Bills{% endblock %}

{% block style %}

    <style>

        table {
            border-collapse: collapse;
            margin: 0 0;
        }

        tr:nth-child(even) {
        {#background-color: darkseagreen;#}
        }


        thead {
            background-color: #1586de;
            color: white;
            line-height: 1.8;
        }

        th, td {
        {#padding: .2em .2em;#} padding: .15em .15em;
            text-align: center;
            width: 45px;
        }

        th:nth-child(1) {
            text-align: center;
            width: 180px;
        {#color: red;#}
        }

        td:nth-child(1) {
            text-align: left;
            color: blue;

        }


        th:nth-child(3) {

            background-color: red;
            color: white;
        }

        td:nth-child(3) {

            color: red;

        }


        th:nth-child(4) {
            text-align: center;
            width: 20px;
        {#color: red;#}
        }

        td:nth-child(4) {
            text-align: left;
            color: blue;

        }


        .eu, .wu, .mc {
            width: 7em;
            text-align: center;
            color: red;
            background-color: lightskyblue;
            margin-left: .25em;

            line-height: 1em;
        }


        .submit button {
            width: 7em;
            font-size: large;
            background-color: red;
            border-color: red;
            border-radius: 15px;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }

        .submit button:hover {
            color: black;
        }

    </style>

{% endblock %}


{% block content %}

    <h1>บิลที่ต้องออกทั้งหมด {{ total_tn }} บิล [ณ. {{ cur_date|date:'d-m-y' }} {{ cur_date|time:'H:i:s' }}] </h1>

    <form action="." method="post">
        {% csrf_token %}
        <div id="create_bill">
            <table>
                <thead>
                <tr>
                    <th>ชื่อ</th>
                    <th>เบอร์โทร.</th>
                    <th>ห้อง</th>
                    <th>ค่าไฟฟ้า</th>
                    <th>ค่าน้ำ</th>
                </tr>
                </thead>
                <tbody>
                {% for t in tpf_billForm_list %}
                    <tr>
                        <td>{{ t.0.tenant }}</td>
                        <td>{{ t.0.phone }}</td>
                        <td>{{ t.0.room_no.room_no }}</td>
                        <td>{{ t.1.elec_unit }}</td>
                        <td>{{ t.1.water_unit }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="submit">
            <button type="submit">ออกบิล</button>
        </div>
    </form>

{% endblock %}

templates/my_app/change_password.html
{% extends "app_base_html.html" %}

{% load static %}

{% block title %}Change password{% endblock %}

{% block style %}
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: helvetica, sans-serif;
        }

        #content {
            padding: 20px 100px;
        }

        div.contract label, div.extra label {
            color: black;
            float: left;
            width: 6em;
            font-weight: bold;
            text-align: right;
            margin-right: .15em;
        }

        #id_pin, #id_phone, #id_room_no, #id_term,
        #id_start_date, #id_end_date, #id_deposit, #id_deduct, #id_cum_ovd, #id_adjust, #id_photo,
        #id_username, #id_first_name, #id_last_name, #id_password, #id_password2 {
            width: 10em;
            background-color: lightblue;
            margin-top: 0;
        }

        div.contract fieldset {
            width: 22em;
            height: 23em;
            float: left;
        }

        div.contract legend {
            color: blue;
            font-weight: bold;
            font-size: 125%;
            margin-bottom: .5em;
        }

        div.extra fieldset {
            width: 18em;
            height: 23em;
        }

        div.extra legend {
            color: blue;
            font-weight: bold;
            font-size: 125%;
            margin-bottom: .5em;
        }

        div.submit button {
            width: 9em;
            font-size: large;
            background-color: red;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Change_password</h1>
{% endblock %}

templates/my_app/maintenanace_charge.html
{% extends "app_base_html.html" %}

{% load static %}
{#{% load widget_tweaks %}#}

{% block title %}New maintenance charge{% endblock %}

{% block script %}
{% endblock %}


{% block style %}
    <style>

        #content {
            font: 90% Arial, Helvetica, sans-serif;
            width: 95%;
            padding: 2em;
            margin: 2px;
        }

        #lb1, #lb2 {
            display: block;

            padding: 1px 5px 1px 1px;
            color: white;
            width: 5em;

            line-height: 1.8em;

            font-size: 110%;
            font-weight: normal;
            text-align: right;
            margin-right: .25em;
            background-color: green;
            float: left;
            clear: both;

        }

        .ma_cost #id_room_no,
        .ma_cost #id_job_cost {
            width: 6em;

            padding: 3px;

            font-size: 110%;

            text-align: center;

            background-color: lightskyblue;
            margin-top: 0;

            float: left;
        }

        .ma_cost fieldset {
            width: 15em;
            height: 9em;

            border-radius: 8px;
        }

        .ma_cost legend {
            color: blue;
            font-weight: bold;
            font-size: 140%;
            margin-bottom: .5em;
        }


        .submit button {
            width: 5.5em;
            font-size: large;
            background-color: red;
            border-color: red;
            border-radius: 15px;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }

        .submit button:hover {
            color: black;
        }
    </style>
{% endblock %}


{% block content %}

    <form action="." method="post">
        {% csrf_token %}
        <div class="ma_cost">
            <fieldset>
                <legend>ค่าบริการ ซ่อมแซม</legend>
                <label for="id_room_no" id="lb1">ห้อง:</label>
                <select id="id_room_no" name="room_no">
                    {% for i in occupied_rm %}
                        <option>{{ i }}</option>
                    {% endfor %}
                </select>

                <br><br><br>
                <label for="id_job_cost" id="lb2">ราคา:</label>
                <input type="number" name="job_cost" id="id_job_cost" min="0" placeholder="บาท" step="any">
            </fieldset>
        </div>
        <div class="submit">
            <button type="submit">ดำเนินการ</button>
        </div>
    </form>

{% endblock %}

templates/my_app/misc_contents.html
{% extends "app_base_html.html" %}
{% load static %}

{% block title %}Misc Contents{% endblock %}

{% block script %}
{% endblock %}

{% block style %}

    <style>

        #topic ul {
            list-style-type: disc;
            color: red;
            font-size: larger;
            font-weight: bold;
        }

        #topic a {
            color: blue;
            text-decoration: none;
        }

        #topic a:hover {
            color: green;
            font-weight: bold;
            text-decoration: none;
        }

        li#manage_us a {
            color: red;
        }

        li#manage_us a:hover {
            color: green;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>รายการ:</h1>
    <div id="topic">
        <ul>
            <li id="manage_us"><p><a href="{% url 'manage_users' %}">จัดการเกี่ยวกับผู้เช่า</a></p></li>
            <li><p><a href="{% url 'maintenance_charge' %}">ค่าบริการซ่อมแซม</a></p></li>
        </ul>
    </div>
{% endblock %}

templates/my_app/monthly_report.html
{% extends 'app_base_html.html' %}
{% load static %}
{% block title %}Create Table{% endblock %}
{% load humanize %}
{% block style %}

    <style>
        figure, figcaption {
            margin: 0;
            padding: 0;
        }

        figure {
        {#border: 1px solid black;#}{#width: 1200px;#}{#padding: 10px;#}{#background-color: lightblue;#}
        }

        figcaption {
        {#display: block;#}{#font-weight: bold;#}{#text-align: center;#}{#font-size: 150%;#}{#padding-bottom: .25em;#}{#background-color: yellow;#}
        }


        table {
            border-collapse: collapse;
        {#border: 2px solid black;#}{#margin: 10px auto;#} margin: 0 0;

        {#background-color: yellow;#}
        }

        th, td {
        {#border: 1px solid black;#} padding: .2em .2em;
            text-align: center;

            width: 80px;
        }

        th.left, td.left {
        {#text-align: left;#}{#width: 220px;#}
        }

        td:nth-child(1) {
        {#text-align: left;#}{#width: 200px;#}
        }

        thead, tfoot {
            background-color: mediumseagreen;
            color: white;

            line-height: 1.5;
        }

        thead th:nth-child(1), tfoot th:nth-child(1) {
            text-align: center;
        }


        tfoot {
            font-weight: bold;
        }

        th:first-child, td:first-child {
            text-align: left;
            width: 200px;

        }

        tbody tr th:nth-child(2), tbody tr td:nth-child(2) {
            text-align: center;
            color: red;
        }

        tr:nth-child(even) {
            background-color: palegreen;
        }

    </style>
{% endblock %}


{% block content %}


    <h1>รายได้ ตึก {{ bld }} เดือน {{ thai_mnth_name }} [ณ. {{ current_date_time|date:'d-m-y' }} {{ current_date_time|time:'H:i:s' }}] </h1>

    <figure>
        {#        <figcaption id="top">Monthly Billing</figcaption>#}
        <table>
            <thead>
            <tr>
                <th class="left">Name</th>
                <th>Room</th>
                <th>RCAC</th>
                <th>EC</th>
                <th>WC</th>
                <th>CSC</th>
                <th>OSC</th>
                <th>OVD</th>
                <th>LF</th>
                <th>MC</th>
                <th>TOTAL</th>
                <th>P_AMT</th>
            </tr>
            </thead>
            <tbody>

            {% for i in all_bills_list %}
                <tr>
                    <td class="left">{{ i.tenant_name }}</td>
                    <td>{{ i.room_no }}</td>
                    <td>{{ i.room_cost|add:i.room_acc_cost|add:i.adjust|floatformat:0|intcomma }}</td>
                    <td>{{ i.electricity_cost|floatformat:0|intcomma }}</td>
                    <td>{{ i.water_cost|floatformat:0|intcomma }}</td>
                    <td>{{ i.common_ser_cost|floatformat:0|intcomma }}</td>
                    <td>{{ i.other_ser_cost|floatformat:0|intcomma }}</td>
                    <td>{{ i.overdue_amount|floatformat:0|intcomma }}</td>
                    <td>{{ i.late_fee|add:i.maint_cost|floatformat:0|intcomma }}</td>
                    <td>{{ i.maint_cost|add:i.maint_cost|floatformat:0|intcomma }}</td>
                    <td>{{ i.bill_total|floatformat:0|intcomma }}</td>
                    <td>{{ i.payment_amount|floatformat:0|intcomma }}</td>
                </tr>
            {% endfor %}
            </tbody>

            <tfoot>
            <tr>
                <th class="left">Total</th>
                <td>All</td>
                <td>{{ trcac|floatformat:0|intcomma }}</td>
                <td>{{ tec|floatformat:0|intcomma }}</td>
                <td>{{ twc|floatformat:0|intcomma }}</td>
                <td>{{ tcsc|floatformat:0|intcomma }}</td>
                <td>{{ tosc|floatformat:0|intcomma }}</td>
                <td>{{ tovd|floatformat:0|intcomma }}</td>
                <td>{{ tlf|floatformat:0|intcomma }}</td>
                <td>{{ tmc|floatformat:0|intcomma }}</td>
                <td>{{ tbt |floatformat:0|intcomma }}</td>
                <td>{{ tpa |floatformat:0|intcomma }}</td>
            </tr>

            </tfoot>
        </table>
        {#        <figcaption id="bottom">Total Sales by Book</figcaption>#}
    </figure>
{% endblock %}

templates/my_app/new_tenant.html
{% extends "app_base_html.html" %}
{% load static %}
{% load humanize %}

{% block title %}Tenant Bil{% endblock %}

{% block script %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}

    <p style="font-size:170%;color: blue">ยินดีต้อนรับ คุณ <span style="color: green; font-size: 1.5em">{{ tenant_name }} ... </span></p>
    <p style="font-size:120%;color: blue"><strong>รายการค่าบริการของท่าน</strong> จะปรากฏ หลังวันที่ 26 ของเดือน</p>
    <p style="font-size:120%;color: blue">โปรดอ่าน <strong>ข้อมูลที่ควรทราบ</strong> ถ้าต้องการความช่วยเหลือใดๆ โทร. 0832461546 (คุณ ต้อม) ได้ตลอดเวลา</p>


{% endblock %}

templates/my_app/payment_tag.html
{% load humanize %}
{% load ams_tags %}

<span class="nam">{{ tenant_bill.tenant_name }} </span>
<span class="rn">{{ tenant_bill.room_no }}</span>
<span class="rcac">{{ rm_c_ac_c_plus_adj|floatformat:0|intcomma }}</span>
<span class="ec">{{ tenant_bill.electricity_cost|floatformat:0|intcomma }}</span>
<span class="wc">{{ tenant_bill.water_cost|floatformat:0|intcomma }}</span>
<span class="csc">{{ tenant_bill.common_ser_cost|floatformat:0|intcomma }}</span>
<span class="osc">{{ tenant_bill.other_ser_cost|floatformat:0|intcomma }}</span>
<span class="ovd">{{ tenant_bill.overdue_amount|floatformat:0|intcomma }}</span>
<span class="misc">{{ bill_misc|floatformat:0|intcomma }}</span>
<span class="bt">{{ tenant_bill.bill_total|floatformat:0|intcomma }}</span>

templates/my_app/report_type.html
{% extends "app_base_html.html" %}
{% load static %}

{% block title %}Report types{% endblock %}

{% block script %}
{% endblock %}

{% block style %}
    <style>
        #topic ul {
            list-style-type: disc;
            color: red;
            font-size: larger;
            font-weight: bold;
        }

        #topic ul a {
            color: blue;
            font-weight: bold;
        }

        #topic ul a:hover {
            color: red;
        }

    </style>
{% endblock %}

{% block content %}
    <h1>รายการ:</h1>
    <div id="topic">
        <ul>
            <li><p><a href="{% url "report_parameters" %}">สรุปรายได้ประจำเดือน</a></p></li>
            <li><p><a href="{% url 'current_tenants' %}">ผู้เช่าปัจจุบัน</a></p></li>
            <li><p><a href="{% url 'vacant_rooms' %}">รายการห้องว่าง</a></p></li>
            <li><p><a href="{% url 'room_type_rate' %}">ประเภทของห้องพร้อมราคา</a></p></li>
            <li><p><a href="{% url 'extra_rates' %}">รายการอื่นๆ พร้อมราคา</a></p></li>

        </ul>
    </div>
{% endblock %}

templates/my_app/water_cpu_change.html
{% extends "app_base_html.html" %}
{% load static %}
{% load humanize %}

{% block title %}Water CPU{% endblock %}

{% block script %}
{% endblock %}

{% block style %}
    <style>
        #da .desc {
            display: block;
        {#width: 9.6em;#} width: 9.8em;
            text-align: left;
            float: left;
            font-size: medium;
            font-weight: bold;
            color: black;
        }

        #da .water_cpu {
            display: block;
            width: 9em;
            text-align: center;
            float: left;
            font-size: medium;
            background-color: powderblue;
        }

        .submit {
            clear: both;
        }

        .submit button {
            width: 6em;
            font-size: large;
            background-color: red;
            border-color: red;
            border-radius: 15px;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }

        .submit button:hover {
            color: black;
        }
    </style>
{% endblock %}

{% block content %}

    <h1>เปลี่ยนค่าน้ำ</h1>

    <div id="da">
        <form action="." method="post">
            {% csrf_token %}
            <span class="desc">ราคาน้ำใหม่ต่อหน่วย:</span>
            {{ water_cpu_form.water_cpu }}
            <br>
            <div class="submit">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock %}